[package]
name = "codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
inkwell = { version = "0.7.0", features = ["llvm21-1"] }
analysis = { path = "../analysis" }
parser = { path = "../parser" }
thiserror = "1.0"
